/*
 * app_signals.h
 *
 *  Created on: Jun 10, 2025
 *      Author: Admin
 */

#ifndef APP_SIGNALS_H_
#define APP_SIGNALS_H_

#include "FSM_signals.h"
/* Event signals */
enum event_signals {
	/* Event signals */
		EVT_SHELL_HAS_DATA = SIG_USER,
		EVT_SHELL_TIMEOUT,
		EVT_SHELL_POLL_TIME,
		EVT_SHELL_SEND_BUFFER,
		EVT_SHELL_SEND_BUFFER_BINARY,
		EVT_SHELL_UART_EMPTY,
		EVT_TIMEOUT ,
		EVT_MIN_POLL,
		EVT_MIN_SHELL_HAS_DATA,
		EVT_MIN_SHELL_POLL_TIME,
		EVT_MIN_SHELL_SEND_BUFFER,
		EVT_TEMPERATURE_CONTROL_TIMEOUT_CONTROL_LOOP,
		EVT_TEMPERATURE_CONTROL_HAS_CMD,
		EVT_MONITOR_NTC_ADC_COMPLETED,
		EVT_MONITOR_LD_ADC_COMPLETED,
		EVT_MONITOR_NTC_TRIGGER_TIME,
		EVT_EXPERIMENT_DATA_AQUISITION_TIMEOUT,
		EVT_EXPERIMENT_START_MEASURE,
		EVT_EXPERIMENT_START_SENDING,
		EVT_EXPERIMENT_FINISH_PRE_SAMPLING,
		EVT_EXPERIMENT_FINISH_SAMPLING,
		EVT_EXPERIMENT_FINISH_POST_SAMPLING,
		EVT_EXPERIMENT_DONE_READ_RAM,
		EVT_EXPERIMENT_DONE_SEND_CHUNK,
		MAX_EVENT_SIG
};


#endif /* APP_SIGNALS_APP_SIGNALS_H_ */
